# Generated by Django 3.0.6 on 2020-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('sex', models.IntegerField(choices=[(1, 'man'), (2, 'woman'), (0, 'unkonw')], verbose_name='sex')),
                ('profession', models.CharField(max_length=128, verbose_name='profession')),
                ('status', models.IntegerField(choices=[(0, 'apply'), (1, 'allow'), (2, 'reject')], default=0, verbose_name='status')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=128, verbose_name='phone')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='creat_time')),
            ],
            options={
                'verbose_name': 'students information',
                'verbose_name_plural': 'students information',
            },
        ),
    ]
